stock_tickers = ['AAPL', 'GOOGL','PG','TCS.BO','MSFT','TWTR','INFY.BO','WIPRO.BO','SBIN.NS',
                'HDFC.NS','ICICIBANK.NS','RELIANCE.NS','TECHM.NS','HINDUNILVR.NS','BHARTIARTL.NS',
                'HCLTECH.NS','ASIANPAINT.NS','LT.NS','AXISBANK.NS','MARUTI.NS','TATAMOTORS.NS','TATASTEEL.NS',
                'NESTLEIND.NS']