stock_tickers = ['AAPL', 'GOOGL','PG','TCS.BO','MSFT','TWTR','NFLX','INFY.BO','WIPRO.BO','SBIN.NS',
                'HDFC.NS','ICICIBANK.NS','RELIANCE.NS','TECHM.NS','HINDUNILVR.NS','BHARTIARTL.NS',
                'HCLTECH.NS','ASIANPAINT.NS','LT.NS','AXISBANK.NS','MARUTI.NS','TATAMOTORS.NS','TATASTEEL.NS',
                'NESTLEIND.NS','AMZN','ACN','ADBE','ORCL','FB','CIPLA6.BO','KPITTECH.NS','BSOFT.NS','LTI.NS','MINDTREE.BO','MPHASIS.NS','NAZARA.NS','NAUKRI.NS',
                'TATAELXSI.NS','HAPPSTMNDS.NS','LUPIN.NS','GLAND.NS','ADANITRANS.NS','ADANIGREEN.NS']